dcat-ap-viewer:
  version: 2
  # Port used for dcat-ap-viewer.
  port: 8030
  # Set to true if you want dcat-ap-viewer to serve static content from
  # "dist" directory. After "npm run build" this directory contains HTML, CSS,
  # JavaScript and other static files. This value should be set to false in
  # a production and static content should be server by other application
  # like Nginx. For more information how visit
  # https://github.com/linkedpipes/dcat-ap-viewer/wiki/Let's-deploy-to-production
  serve-static-content: false
  providers:
  # For more information about providers and their configuration please
  # see https://github.com/linkedpipes/dcat-ap-viewer/wiki/Providers.
    - type: solr
      # Path to the Solr instance, including solr core.
      url: http://localhost:8983/solr/dcat-ap-viewer
      # Default API language.
      default-language: cs
      # List of all languages in Solr.
      languages:
        - cs
        - en
    - type: couchdb
      # Address of
      url: http://127.0.0.1:5984
      # Default API language.
      default-language: cs
    - type: sparql
      # SPARQL endpoint.
      url: http://localhost:8890/sparql
      # We use SPARQL endpoint only for quality related data.
      filter:
        - v2-quality
  client:
    # Name of a profile directory within ./client/ directory.
    # Read readme file in the profile directory to get more information
    # about following options.
    profiles:
      - profile-lkod
    page-title-default: "DCAT-AP Viewer"
    page-title-prefix: ""
    page-title-suffix: " - LP-DAV"
    # Configure URL prefix used to dereference values.
    dereference-url-prefix: ""
    # URL of the dcat-ap forms running instance.
    # https://github.com/linkedpipes/dcat-ap-forms
    dcat-ap-forms-url: ""
    # Used as a fallback and for canonical URL specification.
    default-language: "cs"
    # Template of URL to use for dashboards, with {} as placeholder for IRI.
    dashboards-url-template: "{}"
    # Template of URL to use for detailed dashboards, with {} as placeholder for IRI.
    dashboards-detailed-url-template: "{}"
    # Template of URL to use for "class and types", with {} as placeholder for IRI.
    class-properties-url-template: "{}"
    # Query used for YASGUI instance.
    yasgui-default-query: >
      SELECT ?typ (COUNT(?s) AS ?pocet)
      WHERE {
        ?s a ?typ
      }
      GROUP BY ?typ
      ORDER BY DESC(COUNT(?s))
      LIMIT 10
    # If provided and specification is https://www.w3.org/TR/sparql11-protocol/
    # given values is used as YASGUI endpoint.
    yasgui-url: https://yasgui.triply.cc/
    # URL for semantic themes' browser.
    semantic-browser: https://slovník.gov.cz/prohlížíme/pojem?iri=
    # If set and not empty, then a link to semantic visualisation is shown.
    # The value is appended by encoded dataset IRI and used as URL.
    semantic-visualisation: ""
    # Address of application-catalog, must end with '/'.
    applications-url: """